### ISSUE TITLE
backward compatibility 

### ISSUE THREAD

**Issue by dmitry-a-morozov** [dsyme/SampleMethStaticParamProvider#3]
Hi, 
I'm not sure this is the best medium to ask this question but ...
How this feature will work with VS 2012 & 2013?
Will those methods with static params be ignored or it will cause compilation error?

**Comment by dsyme** [comment]
Hi @dmitry-a-morozov 

Questions on the spec should be raised as PRs, comments or issues here:  https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/StaticMethodArgumentsDesignAndSpec.md

Thanks!
